server:
  port: 8080

spring:
    dataSource:
        jdbc.driverClassName=com.mysql.jdbc.Driver
        jdbc.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
        jdbc.username=root
        jdbc.password=12345678
        jdbc.useSSL=false